# Generated by Django 5.2.7 on 2025-11-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="URL to project image/screenshot", null=True
            ),
        ),
    ]
